<div class="home-widgets-top">
    <?php $groupData = $this->getDataByGroupCode() ?>
    <?php if (isset($groupData['banner_data'])): ?>
        <?php foreach ($groupData['banner_data'] as $banner): ?>
            <a class="home-widget-top" href="<?php echo $banner->getLink() ?>">
                <img alt="<?php echo $banner->getTitle() ?>" src="<?php echo $this->getBannerImageUrl($banner) ?>"/>
                <span class="home-widget-overlay"><?php echo $banner->getTitle() ?></span>
            </a>
        <?php endforeach; ?>
    <?php endif; ?>
</div>