<?php if((bool)Mage::getStoreConfig("aldress/color/enable")): ?>
<div id="colorPalette">
    <div id="palette-control" class="fa fa-paint-brush"></div>
    <div id="palette-body">
        <div class="palette-label"><?php echo $this->__('Like own color? Select it!') ?></div>
        <input id="palette-color" type="color" value="#712c6b" />
		<div id="palette-reset"><?php echo $this->__('Reset default') ?></div>
    </div>
</div>
<?php endif ?>